### ISSUE TITLE
Suggestion: add toy data set to streamlit app

### ISSUE THREAD

**Issue by JamesHWade** [geemi725/XpertAI#12]
Cool work!

I recommend adding an example dataset to the streamlit app so that it's easier to explore. Maybe having a few (small) datasets in the repo could work too.

I get an error when I try to add my own data, but I'm not sure if that's a bug or me not properly formatting the data.

**Comment by geemi725** [comment]
Hi James! Thank you for the suggestion, definitely valuable. Will address this issue ASAP

**Comment by geemi725** [comment]
@JamesHWade  A "test run" option is now added to the streamlit app. You can download this toy dataset after the run along with test outputs. 

Closing this issue for now. Thank you for your suggestion!
